### ISSUE TITLE
Is it available for HTML/CSS/JavaScript web page ?

### ISSUE THREAD

**Issue by pascalf22** [tommoor/emojione-picker#103]
Hello !

I'm really interested by emojione-picker! Is it available for normal html page ?
Thanks a lot !

**Comment by tommoor** [comment]
You can use the component anywhere you like, but you'll also have to include React to render the UI. There is no bundled version available without React

**Comment by pascalf22** [comment]
Ok thanks ! I appreciate ! 
Pascal
