### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by rcdelacruz** [tommoor/emojione-picker#11]
I got this error:

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "emojione-picker"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for /var/folders/kh/sy_bkwjn3n7fsf2zbgrysb580000gp/T/npm-2582-81be861c/registry.npmjs.org/emojione/-/emojione-2.1.0.tgz
npm ERR! Expected: d0100d67661baaba2258e7033e3b0c614c722f5b
npm ERR! Actual:   4dd64b2fdc54a6b1b70e62e033eb2a72c64f972a
npm ERR! From:     http://registry.npmjs.org/emojione/-/emojione-2.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by tommoor** [comment]
Hey, this is a problem with NPM or your installation - not the module. There are a couple of possible solutions at the bottom of this thread:

https://github.com/npm/npm/issues/2701

Hope it helps
