### ISSUE TITLE
Use official strategy

### ISSUE THREAD

**Issue by tleunen** [tommoor/emojione-picker#23]
Emojione provides a strategy file. I think it would be best if the component uses the official file instead: https://github.com/Ranks/emojione/blob/master/emoji_strategy.json

It would allow an easier update to Emojione version as well in the future :)

**Comment by tommoor** [comment]
Great idea, I moved to loading the strategy from within the emojione package - this meant a breaking change as they have renamed the category 'foods' to 'food' - I published this with a new major version `1.0.0`

closed by 457f5aad7a6a3fcfed7d8194da96a448b010e2f5
