### ISSUE TITLE
First render performance

### ISSUE THREAD

**Issue by tommoor** [tommoor/emojione-picker#3]
First render performance is poor due to the massive amount of emojis we have here, I have a few ideas to speed up the perceived load...

- [x] Do a first pass render with just the dialog and headers
- [x] Render the emojis in category chunks
- [ ] Move to faster loops (remove underscore?)

**Comment by ronhornbaker** [comment]
I'm seeing 45 seconds after first load until an emoji click registers in the console, on a late-model MBA with latest Chrome. Diving into speeding that up now.
