### ISSUE TITLE
Performance issues on `render()`

### ISSUE THREAD

**Issue by omichelsen** [tommoor/emojione-picker#38]
I am using your lib inside my chat input component, which uses textarea `onChange` when user enters something to update the state. However this state change triggers EmojiPicker to render every time the user presses a key. Understandably this causes CPU use to go through the roof and input slows to a crawl.

Suggestion:

Add `shouldComponentRender()` handling using fx `react-addons-shallow-compare`:

``` js
shouldComponentUpdate(nextProps, nextState) {
  return shallowCompare(this, nextProps, nextState);
}
```

**Comment by tommoor** [comment]
Thanks for bringing this up, it should be much better in `2.0` - https://github.com/tommoor/emojione-picker/releases/tag/v2.0.0
