### ISSUE TITLE
Emoji files cannot be loaded

### ISSUE THREAD

**Issue by EllisShen** [tommoor/emojione-picker#41]
Hi I'm developing an Electron based application and use emojione-picker. However I soon noticed a serious issue that all emoji files (png and svg) couldn't be loaded since there's no specific **schema** defined. In the **preview.js**, the src is setup like `src="//cdn.jsdelivr.net/emojione/assets/png/1f91e.png?v=2.2.6:1"` which would be interpreted into *\* file://*\* schema in Electron...

Is there a better way to override the src schema or how about specify the schema as http:// somewhere in the code?

**Comment by tommoor** [comment]
Hey @EllisShen, I'd probably recommend downloading the assets into your Electron application and creating a modified css file that maps to their local location rather than reading from the network for a desktop app.
