### ISSUE TITLE
Search doesn't work as expected

### ISSUE THREAD

**Issue by bradbirnbaum** [tommoor/emojione-picker#43]
In search when I search for `poop` I would expect the poop icon to surface.   The issue is that the regex for search is off of the keywords but it also should be off the name

**Comment by ahutchings** [comment]
This regex seems to work pretty well for finding emoji based on the name, and matches the rules the built-in MacOS emoji picker uses to match partial phrases:

```js
new RegExp(`^(?:.* +)*${term}`, 'i');
```

I have this working in a local branch built on top of the changes in #50 and will submit a pull request once that moves forward.
