### ISSUE TITLE
Huge performance hit when loading emoji picker

### ISSUE THREAD

**Issue by Orbyt** [tommoor/emojione-picker#45]
I'm trying out a slightly modified version of this package in two seperate projects. In one (which is an Electron applicatoin), for all intents and purposes of this issue, it works as expected.

The other is a small widget built with React. I ported over the Emoji Picker from the other project, but when opening the picker in the widget, the various emojis load extremely slow (~2 seconds) and cause the widget to become unresponsive. 

What might be causing this issue?

**Comment by tommoor** [comment]
Thanks for bringing this up, it should be much better in `2.0` - https://github.com/tommoor/emojione-picker/releases/tag/v2.0.0
