### ISSUE TITLE
convertion from short name to emoji in chat

### ISSUE THREAD

**Issue by suganya-g** [tommoor/emojione-picker#46]
when i used emojione-picker in my chat module , when clicking on one emoji i could fetch the shortname in my chattext but when clicking on chat send,the shortname was not converted to the exact emoji as expected.what is the problem?? should i have to define a method to convert shortname to emoji??

**Comment by tommoor** [comment]
Hi @suganya-g - this module is only a UI picker, all other operations around converting and handling emojis would need to be provided by your own code.
