### ISSUE TITLE
people filter doen't work

### ISSUE THREAD

**Issue by SnowDiamond** [tommoor/emojione-picker#47]
Hi! First of all thank you for great lib! I'm facing with some problem: when I click on any people filters button nothing happens. I expect that images should be filtered. Any ideas?
![2017-01-04 13 38 44](https://cloud.githubusercontent.com/assets/9202886/21641285/7ab45e2a-d283-11e6-85b9-adcf60bc29df.png)

If there is no any way to make it work correct, maybe it possible to hide this filter?

**Comment by SnowDiamond** [comment]
I hide this section just with css:

```
.emoji-dialog .modifiers {
  display: none;
}
```

**Comment by tommoor** [comment]
Hey @SnowDiamond you can absolutely feel free to hide this control. It does work, however only some emoji provide skin tone modifiers - they are all at the end of the people category, eg:

![image](https://cloud.githubusercontent.com/assets/380914/21739537/3ce23592-d452-11e6-890b-4f4d42058316.png)
