### ISSUE TITLE
Hide modifiers if not required

### ISSUE THREAD

**Issue by dineshvgp** [tommoor/emojione-picker#57]
Is there a way to disable modifiers?
If not shall I raise a PR?

I don't want to hide it using css instead I do not need to render it.

**Comment by tommoor** [comment]
Hey Dinesh,

There is not an option to hide modifiers right now - intrigued as to your
usecase for removing this? 💁🏼‍♂️

**Comment by dineshvgp** [comment]
Hey Tom Moor,

I'm working for a commercial app in which the requirement is not to show skin color.

**Comment by tommoor** [comment]
Skin tone modifiers are important, I don't want to support removing them in the official module - feel free to fork and remove them for your own use which I'm guessing is what you ended up doing here 😉
