### ISSUE TITLE
Search does not search shortnames

### ISSUE THREAD

**Issue by csu** [tommoor/emojione-picker#66]
It looks like the emoji picker doesn't currently use emoji shortnames when searching. This causes some queries that should intuitively work to not return the expected results.

For example, searching for "wave" does not return the 👋 emoji, which has the shortcode `:wave:`. Searching for "wav" returns it, because the emoji is named "waving hand sign", but searching for "wave" does not.

**Comment by tommoor** [comment]
<img width="320" alt="screen shot 2017-04-19 at 22 17 33" src="https://cloud.githubusercontent.com/assets/380914/25214803/5b775b2a-254e-11e7-8fd9-884727582762.png">
