### ISSUE TITLE
Support Content Security Policy

### ISSUE THREAD

**Issue by akihikodaki** [tommoor/emojione-picker#68]
[The specification of Content Security Policy](https://www.w3.org/TR/2016/REC-CSP2-20161215/#intro)
describes as the following:

> This document defines Content Security Policy, a mechanism web applications can use to mitigate a broad class of content injection vulnerabilities, such as cross-site scripting (XSS).

To apply Content Security Policy, we need to set a nonce to `style` element appended by _react-virtualized_. I have made a change for _react-virtualized_. (https://github.com/bvaughn/react-virtualized/pull/663)

_emojione-picker_ is also required to be altered to correspond the change. I have also finished to create a change for _emojione-picker_ fcb244dc2f0fe82a5136501171c828c7332c4b4b, but we may wait for a new version of _react-virtualized_ including its Content Security Policy support.

**Comment by tommoor** [comment]
It seems like this is tied to https://github.com/tommoor/emojione-picker/issues/67 - perhaps both changes could be made at the same time?

**Comment by akihikodaki** [comment]
Yes, just by replacing the change of `package.json`  and `yarn.lock` in commit fcb244dc2f0fe82a5136501171c828c7332c4b4b. I will make a pull request soon.

**Comment by tommoor** [comment]
closed in d13681972c7d2b10edd9e74b7766f22cbed7a090
