### ISSUE TITLE
Chrome on Ubuntu, the modifiers don't work

### ISSUE THREAD

**Issue by ciprian-chichirita** [tommoor/emojione-picker#76]
The modifiers don't work on Chrome/firefox (both running on ubuntu as OS).

![image](https://user-images.githubusercontent.com/11610060/29363241-e19a222c-8297-11e7-9476-c22c2e9de3a7.png)

**Comment by tommoor** [comment]
I'm not sure why this would happen - can you show an example? Note the color modifiers only affect some emoji.

**Comment by ciprian-chichirita** [comment]
yeap, it is what you said, you can close this issue.

Trivia: any ideas how I can replace the searc placeHolder text?

**Comment by tommoor** [comment]
Ah yes - there is a `searchPlaceholder` prop for this purpose 😄
