### ISSUE TITLE
Warnings in react 15.6

### ISSUE THREAD

**Issue by stevenmusumeche** [tommoor/emojione-picker#77]
When upgrading to the latest version of emojione-picker with React 15.6, I have the following error in the console:

Warning: Failed prop type: The prop `tabIndex` is marked as required in `Grid`, but its value is `null`.

**Comment by stevenmusumeche** [comment]
@tommoor PR here: https://github.com/tommoor/emojione-picker/pull/78

**Comment by ahutchings** [comment]
This was fixed upstream in react-virtualized. Anyone running into this needs to update react-virtualized to 9.11.0 or later.
